version: '3.8'

services:
  api-node-1:
    image: link-shortner-dev
    volumes:
      - ./data/:/app/data/
    ports:
      - "8001:8080"
    environment:
      - LINKS_PATH = ./data/links.json
  
  echo_node:
    image: link-shortner-dev
    depends_on:
      - api-node-1
    volumes:
      - ./data/:/app/data/
    ports:
      - "8002:8080"
    environment:
      - LINKS_PATH = ./data/links.json
    command: ["echo", "system is fine!"]    

  api-node-2:
    image: link-shortner-dev
    volumes:
      - ./data/:/app/data/
    ports:
      - "8003:8080"
    environment:
      - LINKS_PATH = ./data/links.json
  
  api-node-3:
    image: link-shortner-dev
    volumes:
      - ./data/:/app/data/
    ports:
      - "8004:8080"
    environment:
      - LINKS_PATH = ./data/links.json