version: '3.8'

x-common-api-settings: &common-settings
    image: link-shortner-dev
#    build:
#     context: .
#     dockerfile: Dockerfile
    volumes:
      - ./data/:/app/data/
    environment:
      - LINKS_PATH = ./data/links.json
    healthcheck:
      test: ["CMD","curl","localhost:8080/api/health_check"]
      interval: 30s
      timeout: 3s
      retries: 2
    deploy:
      resources:
      limits:
        cpus: '1'
        memory: 100m
      reservations:
        cpus: '0.5'
        memory: 10m

services:
  api-node-1:
    <<: *common-settings
    ports:
      - "8001:8080"
  echo_node:
    <<: *common-settings
    depends_on:
      - api-node-1
    ports:
      - "8002:8080"
    command: ["echo", "system is fine!"]    
  api-node-2:
    <<: *common-settings
    ports:
      - "8003:8080"
  api-node-3:
    <<: *common-settings
    ports:
      - "8004:8080"